### ISSUE TITLE
Jack error + environment variables problems

### ISSUE THREAD

**Issue by GRBurst** [jfloff/docker-lineageos#1]
Hey,

thanks for this nice docker image!

I just tried this docker image to build an example bacon image.
```
[ 38% 13362/34470] Ensure Jack server is installed and started
FAILED: /bin/bash -c "(prebuilts/sdk/tools/jack-admin install-server prebuilts/sdk/tools/jack-launcher.jar prebuilts/sdk/tools/jack-server-4.8.ALPHA.jar  2>&1 || (exit 0) ) && (JACK_SERVER_VM_ARGUMENTS=\"\"-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx8G\"\" prebuilts/sdk/tools/jack-admin start-server 2>&1 || exit 0 ) && (prebuilts/sdk/tools/jack-admin update server prebuilts/sdk/tools/jack-server-4.8.ALPHA.jar 4.8.ALPHA 2>&1 || exit 0 ) && (prebuilts/sdk/tools/jack-admin update jack prebuilts/sdk/tools/jacks/jack-2.28.RELEASE.jar 2.28.RELEASE || exit 47; prebuilts/sdk/tools/jack-admin update jack prebuilts/sdk/tools/jacks/jack-3.36.CANDIDATE.jar 3.36.CANDIDATE || exit 47; prebuilts/sdk/tools/jack-admin update jack prebuilts/sdk/tools/jacks/jack-4.7.BETA.jar 4.7.BETA || exit 47 )"
Writing client settings in /home/lineageos/.jack-settings
Installing jack server in "/home/lineageos/.jack-server"
/bin/bash: -XX:+TieredCompilation: command not found
No Jack server running. Try 'jack-admin start-server'
No Jack server running. Try 'jack-admin start-server'
[ 38% 13362/34470] host C++: libconscrypt_openjdk_jni <= external/conscrypt/src/main/native/org_conscrypt_NativeCrypto.cpp
ninja: build stopped: subcommand failed.
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1
make: Leaving directory '/home/lineageos'

#### make failed to build some targets (46:12 (mm:ss)) ####
```

It states that jack is not running.
Starting it manually by just typing `jack-admin start-server` does not take `ANDROID_JACK_VM_ARGS` into account. So how is it intended to be used?

Further more, the environment variables do not get substituted / expanded properly. If I set `CCACHE_DIR=$BASE_DIR/ccache`, a directory $BASE_DIR is created as top folder for the ccache and if set it to `CCACHE_DIR="$BASE_DIR/ccache"` a directory " is created on top level. This happens even if define it after defining BASE_DIR. Am I missing something here?

Thanks for your help in advance :-)

**Comment by jfloff** [comment]
Hello,

This image started as my own use, so having this feedback is excellent! Thank you in advance :)

Could you show me the steps you took to start building the image?


Thank you!

**Comment by GRBurst** [comment]
Hey,

thanks for your reply!

EDIT:
> For sake of completeness: I pulled `docker pull jfloff/lineageos`

I called it with the following parameters:
```
docker run --rm --privileged -v $(pwd)/android:/home/lineageos --env-file dockerbuild/bacon.env -ti jfloff/lineageos
```

the `bacon.env` contains the following:
```
#!/bin/bash
GIT_USER_NAME=GRBurst
GIT_USER_EMAIL=[masked]
BASE_DIR=/home/lineageos
LINEAGEOS_REPO=https://github.com/LineageOS/android.git
LINEAGEOS_BRANCH=cm-14.1
USE_CCACHE=1
CCACHE_SIZE=75G
CCACHE_COMPRESS=1
CCACHE_DIR=/home/lineageos/ccache
ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx8G"
WITH_SU=false
DEVICE_CODENAME=bacon
PROPRIETARY_BLOBS_REPO=https://github.com/TheMuppets/proprietary_vendor_oneplus
PROPRIETARY_BLOBS_DIR=/home/lineageos/vendor/oneplus
```

I masked the E-Mail above, but I set a correct one in `bacon.env`.
As you can see I hardcoded the paths for e.g. CCACHE. That is not really an issue but I would prefere to write it like that:
```
#!/bin/bash
GIT_USER_NAME=GRBurst
GIT_USER_EMAIL=[masked]
BASE_DIR="/home/$USER"
LINEAGEOS_REPO=https://github.com/LineageOS/android.git
LINEAGEOS_BRANCH=cm-14.1
USE_CCACHE=1
CCACHE_SIZE=75G
CCACHE_COMPRESS=1
CCACHE_DIR="$BASE_DIR/ccache"
ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx8G"
WITH_SU=false
DEVICE_CODENAME=bacon
PROPRIETARY_BLOBS_REPO=https://github.com/TheMuppets/proprietary_vendor_oneplus
PROPRIETARY_BLOBS_DIR="$BASE_DIR/vendor/oneplus"
```

**Comment by jfloff** [comment]
Just so you know, I'm looking at it! Just holidays are in the way :)

Happy new year!

**Comment by GRBurst** [comment]
Hey thanks and a happy new year to you, too :-)

I just played a bit and read your code. The problem concerning the environment variables seems to be caused by just sourcing them, but instead, you must force them to get expanded.
As far as I understand this can be achieved using `envsubst` in the init.sh script, see [SO](https://stackoverflow.com/questions/10683349/forcing-bash-to-expand-variables-in-a-string-loaded-from-a-file?answertab=active#tab-top).

**Comment by jfloff** [comment]
Sorry about being slow answering this, thing is I was struggling with my computer and didn't had enough space to build android. I think its all good now.

Question, could you paste the output of `printenv` once you are inside the container? Let's focus on the 2nd version of your .env file, the one you think should work.
Run the container only with `printenv`:
```
docker run --rm --privileged -v $(pwd)/android:/home/lineageos --env-file dockerbuild/bacon.env -ti jfloff/lineageos printenv
```

Paste the output so I can check :)

Thank you so much! Let's fix this 💪

**Comment by jfloff** [comment]
I found out that this is a problem from the Docker `env-file` parameter. It doesn't interpret variables in a bash-like way (https://github.com/moby/moby/issues/26009).

This is clearly visible when I backup the current environment (https://github.com/jfloff/docker-lineageos/blob/master/init.sh#L8), it comes with all the quotes and dollar escaped:
```
declare -x BASE_DIR="\"/home/\$USER\""
declare -x CCACHE_DIR="\"\$BASE_DIR/ccache\""
declare -x PROPRIETARY_BLOBS_DIR="\"\$BASE_DIR/vendor/oneplus\""
```

According to their PR (https://github.com/moby/moby/pull/28092#issuecomment-273873571) implementing this would be like implementing another shell. However, we need some solution for this. I think the best way would be to do some `sed`ing on the result of `declare -xp`, we unescape the first and last quotes and the dollar signs. 

I'm thinking of replacing https://github.com/jfloff/docker-lineageos/blob/master/init.sh#L8 with something along these lines: 
```
declare -px | sed -e 's/"\\"/"/g; s/\\""/"/g; s/\\\$/\$/g' > /tmp/current.env
```

What do you think? Its not perfect, but that's what could be done with Docker's limitation.

**Comment by GRBurst** [comment]
Okay that one is ugly but if it works :grinning:

**Comment by jfloff** [comment]
Yes, it is indeed ... You do whatcha gotta do :)

**Comment by jfloff** [comment]
Ok, I also was able to `init` and `build` with your bacon details. I'm even adding them to the repository, feel free to edit them afterwards. 

I guess this closes the issue. Commit incoming and new builds for Docker Hub also on the way.

**Comment by jfloff** [comment]
Build on DockerHub updated.

Also, here is the new [bacon.env](https://github.com/jfloff/docker-lineageos/blob/master/device-config/bacon.env) file. Check if it has the right values.

Thank you for your help! Sorry about the delay

**Comment by jfloff** [comment]
@GRBurst could you confirm me that everything is working?

**Comment by GRBurst** [comment]
@jfloff yes, I will try it on the weekend :-)
