### ISSUE TITLE
local manifest

### ISSUE THREAD

**Issue by monthadar** [jfloff/docker-lineageos#6]
Hi,

I have two questions.

1) What do you think of adding extra environment variables to default.env for adding a local manifest as part of the init process? 
My use case is, I want to build e.g. grouper on lineageOS. So I can just point to a git repo with a local manifest that will be added before the first sync, example local manifest:

> https://github.com/aperomsik/lineageos_local_manifests.git

So one only needs to modify default.env file, maybe with something like following?:
`# Repo and branch for a local manifest`
`LINEAGEOS_LOCAL_MANIFEST_REPO=https://github.com/aperomsik/lineageos_local_manifests.git`
`LINEAGEOS_LOCAL_MANIFEST_BRANCH=cm-14.1`

I think there is a good way to utilize what features repo have for different flavors of builds. If you think it's a good feature I can create a pull request.

2) I see that in the init function you don't call the sync function any reason for not doing it?

Thanks!

**Comment by jfloff** [comment]
Hi there! Sorry for the late reply but I was out of office last week.

> 1. What do you think of adding extra environment variables to default.env for adding a local manifest as part of the init process?

I think that is a good idea and quite easy to add! I guess the default would be no manifest? 

Are you moving forward with the PR?


> 2. I see that in the init function you don't call the sync function any reason for not doing it?

Mmm, isn't [this](https://github.com/jfloff/docker-lineageos/blob/master/lineageos#L120) it?

**Comment by monthadar** [comment]
> Hi there! Sorry for the late reply but I was out of office last week.
> 
> > 1. What do you think of adding extra environment variables to default.env for adding a local manifest as part of the init process?
> 
> I think that is a good idea and quite easy to add! I guess the default would be no manifest?
> 
> Are you moving forward with the PR?

Just created a pull request.

> 
> > 1. I see that in the init function you don't call the sync function any reason for not doing it?
> 
> Mmm, isn't [this](https://github.com/jfloff/docker-lineageos/blob/master/lineageos#L120) it?

Yes, I meant why not call [sync function](https://github.com/jfloff/docker-lineageos/blob/master/lineageos#L181) from the line you [referenced](https://github.com/jfloff/docker-lineageos/blob/master/lineageos#L120)?

**Comment by jfloff** [comment]
Oh I see ... that looks like a good idea also :) Do you mind PRing that change as well?

Thank you!

**Comment by monthadar** [comment]
Done!

**Comment by jfloff** [comment]
Thank you for the PRs! Merged and building new images 👍
